// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PENTING: Ganti konfigurasi ini dengan konfigurasi Firebase Anda.
/// Jalankan `flutterfire configure` untuk generate file ini secara otomatis.
///
/// Langkah-langkah:
/// 1. Buat project di Firebase Console (https://console.firebase.google.com)
/// 2. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
/// 3. Jalankan: `flutterfire configure`
/// 4. File ini akan otomatis ter-overwrite dengan konfigurasi yang benar
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions tidak support untuk platform ini.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXr4iDHgM0XmsFt0zrlSsaMDNuP6q4IwI',
    appId: '1:912693980258:web:b175ce5b288840462c353b',
    messagingSenderId: '912693980258',
    projectId: 'laundry-bfe40',
    authDomain: 'laundry-bfe40.firebaseapp.com',
    storageBucket: 'laundry-bfe40.firebasestorage.app',
    measurementId: 'G-2B62P795Y3',
  );

  // TODO: Ganti dengan konfigurasi Firebase Web Anda

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4FI81Lb-YPUDX0LTCJ2kQpg32gMDJp8',
    appId: '1:912693980258:android:c94ff0b108418bc02c353b',
    messagingSenderId: '912693980258',
    projectId: 'laundry-bfe40',
    storageBucket: 'laundry-bfe40.firebasestorage.app',
  );

  // TODO: Ganti dengan konfigurasi Firebase Android Anda

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83I0EhugdXcCGbdHhWOLEWRY-73JJkaA',
    appId: '1:912693980258:ios:943f9882e0ac083d2c353b',
    messagingSenderId: '912693980258',
    projectId: 'laundry-bfe40',
    storageBucket: 'laundry-bfe40.firebasestorage.app',
    iosBundleId: 'com.laundrykuy.laundryKuy',
  );

  // TODO: Ganti dengan konfigurasi Firebase iOS Anda
}