// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PENTING: Ganti konfigurasi ini dengan konfigurasi Firebase Anda.
/// Jalankan `flutterfire configure` untuk generate file ini secara otomatis.
///
/// Langkah-langkah:
/// 1. Buat project di Firebase Console (https://console.firebase.google.com)
/// 2. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
/// 3. Jalankan: `flutterfire configure`
/// 4. File ini akan otomatis ter-overwrite dengan konfigurasi yang benar
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions tidak support untuk platform ini.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXwOpuSyXfoHXNWoj4b7cRcrmMHRkDjfE',
    appId: '1:749779589895:web:afb17bce0df38792a143a2',
    messagingSenderId: '749779589895',
    projectId: 'laundrykuy-652c0',
    authDomain: 'laundrykuy-652c0.firebaseapp.com',
    storageBucket: 'laundrykuy-652c0.firebasestorage.app',
    measurementId: 'G-0G814KHW97',
  );

  // TODO: Ganti dengan konfigurasi Firebase Web Anda

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCjqaXJZ1TeTkwKK13XViWuYkiWyzqbK4',
    appId: '1:749779589895:android:12b12ec857c5150fa143a2',
    messagingSenderId: '749779589895',
    projectId: 'laundrykuy-652c0',
    storageBucket: 'laundrykuy-652c0.firebasestorage.app',
  );

  // TODO: Ganti dengan konfigurasi Firebase Android Anda

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_htVfKzdVI3_T6N0RRD-SGIkvB_Ufgw',
    appId: '1:749779589895:ios:b455f8c22688b6b8a143a2',
    messagingSenderId: '749779589895',
    projectId: 'laundrykuy-652c0',
    storageBucket: 'laundrykuy-652c0.firebasestorage.app',
    iosClientId:
        '749779589895-p514lp86ao01062512fjh60964gcvds5.apps.googleusercontent.com',
    iosBundleId: 'com.laundrykuy.laundryKuy',
  );

  // TODO: Ganti dengan konfigurasi Firebase iOS Anda
}
